// Generated by gencpp from file robostilt_common/empty_call_bool_ResultResponse.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_EMPTY_CALL_BOOL_RESULTRESPONSE_H
#define ROBOSTILT_COMMON_MESSAGE_EMPTY_CALL_BOOL_RESULTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robostilt_common
{
template <class ContainerAllocator>
struct empty_call_bool_ResultResponse_
{
  typedef empty_call_bool_ResultResponse_<ContainerAllocator> Type;

  empty_call_bool_ResultResponse_()
    : result(false)  {
    }
  empty_call_bool_ResultResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct empty_call_bool_ResultResponse_

typedef ::robostilt_common::empty_call_bool_ResultResponse_<std::allocator<void> > empty_call_bool_ResultResponse;

typedef boost::shared_ptr< ::robostilt_common::empty_call_bool_ResultResponse > empty_call_bool_ResultResponsePtr;
typedef boost::shared_ptr< ::robostilt_common::empty_call_bool_ResultResponse const> empty_call_bool_ResultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robostilt_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robostilt_common': ['/home/fernandomierhicks/robostilt/src/robostilt_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robostilt_common/empty_call_bool_ResultResponse";
  }

  static const char* value(const ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
";
  }

  static const char* value(const ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct empty_call_bool_ResultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robostilt_common::empty_call_bool_ResultResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_EMPTY_CALL_BOOL_RESULTRESPONSE_H
