// Generated by gencpp from file robostilt_common/LowerLegsOnFrame.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_LOWERLEGSONFRAME_H
#define ROBOSTILT_COMMON_MESSAGE_LOWERLEGSONFRAME_H

#include <ros/service_traits.h>


#include <robostilt_common/LowerLegsOnFrameRequest.h>
#include <robostilt_common/LowerLegsOnFrameResponse.h>


namespace robostilt_common
{

struct LowerLegsOnFrame
{

typedef LowerLegsOnFrameRequest Request;
typedef LowerLegsOnFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LowerLegsOnFrame
} // namespace robostilt_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robostilt_common::LowerLegsOnFrame > {
  static const char* value()
  {
    return "b8d63a087f5948862a72cd21437ca0f9";
  }

  static const char* value(const ::robostilt_common::LowerLegsOnFrame&) { return value(); }
};

template<>
struct DataType< ::robostilt_common::LowerLegsOnFrame > {
  static const char* value()
  {
    return "robostilt_common/LowerLegsOnFrame";
  }

  static const char* value(const ::robostilt_common::LowerLegsOnFrame&) { return value(); }
};


// service_traits::MD5Sum< ::robostilt_common::LowerLegsOnFrameRequest> should match 
// service_traits::MD5Sum< ::robostilt_common::LowerLegsOnFrame > 
template<>
struct MD5Sum< ::robostilt_common::LowerLegsOnFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::LowerLegsOnFrame >::value();
  }
  static const char* value(const ::robostilt_common::LowerLegsOnFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::LowerLegsOnFrameRequest> should match 
// service_traits::DataType< ::robostilt_common::LowerLegsOnFrame > 
template<>
struct DataType< ::robostilt_common::LowerLegsOnFrameRequest>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::LowerLegsOnFrame >::value();
  }
  static const char* value(const ::robostilt_common::LowerLegsOnFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robostilt_common::LowerLegsOnFrameResponse> should match 
// service_traits::MD5Sum< ::robostilt_common::LowerLegsOnFrame > 
template<>
struct MD5Sum< ::robostilt_common::LowerLegsOnFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::LowerLegsOnFrame >::value();
  }
  static const char* value(const ::robostilt_common::LowerLegsOnFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::LowerLegsOnFrameResponse> should match 
// service_traits::DataType< ::robostilt_common::LowerLegsOnFrame > 
template<>
struct DataType< ::robostilt_common::LowerLegsOnFrameResponse>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::LowerLegsOnFrame >::value();
  }
  static const char* value(const ::robostilt_common::LowerLegsOnFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_LOWERLEGSONFRAME_H
