// Generated by gencpp from file robostilt_common/MovePrismaticRevolute.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_MOVEPRISMATICREVOLUTE_H
#define ROBOSTILT_COMMON_MESSAGE_MOVEPRISMATICREVOLUTE_H

#include <ros/service_traits.h>


#include <robostilt_common/MovePrismaticRevoluteRequest.h>
#include <robostilt_common/MovePrismaticRevoluteResponse.h>


namespace robostilt_common
{

struct MovePrismaticRevolute
{

typedef MovePrismaticRevoluteRequest Request;
typedef MovePrismaticRevoluteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePrismaticRevolute
} // namespace robostilt_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robostilt_common::MovePrismaticRevolute > {
  static const char* value()
  {
    return "565c8a3a9e59566cc3f236fd9834581d";
  }

  static const char* value(const ::robostilt_common::MovePrismaticRevolute&) { return value(); }
};

template<>
struct DataType< ::robostilt_common::MovePrismaticRevolute > {
  static const char* value()
  {
    return "robostilt_common/MovePrismaticRevolute";
  }

  static const char* value(const ::robostilt_common::MovePrismaticRevolute&) { return value(); }
};


// service_traits::MD5Sum< ::robostilt_common::MovePrismaticRevoluteRequest> should match 
// service_traits::MD5Sum< ::robostilt_common::MovePrismaticRevolute > 
template<>
struct MD5Sum< ::robostilt_common::MovePrismaticRevoluteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::MovePrismaticRevolute >::value();
  }
  static const char* value(const ::robostilt_common::MovePrismaticRevoluteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::MovePrismaticRevoluteRequest> should match 
// service_traits::DataType< ::robostilt_common::MovePrismaticRevolute > 
template<>
struct DataType< ::robostilt_common::MovePrismaticRevoluteRequest>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::MovePrismaticRevolute >::value();
  }
  static const char* value(const ::robostilt_common::MovePrismaticRevoluteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robostilt_common::MovePrismaticRevoluteResponse> should match 
// service_traits::MD5Sum< ::robostilt_common::MovePrismaticRevolute > 
template<>
struct MD5Sum< ::robostilt_common::MovePrismaticRevoluteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::MovePrismaticRevolute >::value();
  }
  static const char* value(const ::robostilt_common::MovePrismaticRevoluteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::MovePrismaticRevoluteResponse> should match 
// service_traits::DataType< ::robostilt_common::MovePrismaticRevolute > 
template<>
struct DataType< ::robostilt_common::MovePrismaticRevoluteResponse>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::MovePrismaticRevolute >::value();
  }
  static const char* value(const ::robostilt_common::MovePrismaticRevoluteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_MOVEPRISMATICREVOLUTE_H
