// Generated by gencpp from file robostilt_common/RobotState.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_ROBOTSTATE_H
#define ROBOSTILT_COMMON_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robostilt_common
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : header()
    , state(0)
    , state_string()
    , fault(0)
    , fault_string()  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , state_string(_alloc)
    , fault(0)
    , fault_string(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_string_type;
  _state_string_type state_string;

   typedef int32_t _fault_type;
  _fault_type fault;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fault_string_type;
  _fault_string_type fault_string;



  enum {
    STATE_READY = 0,
    STATE_FAULTED = 1,
    STATE_BUSY_MOVING = 2,
    STATE_BUSY_COMPUTING = 3,
    FAULT_CLEAR = 0,
    FAULT_ESTOP = 1,
    FAULT_EFFORT = 2,
    FAULT_TRAJECTORY = 3,
  };


  typedef boost::shared_ptr< ::robostilt_common::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robostilt_common::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::robostilt_common::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::robostilt_common::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::robostilt_common::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robostilt_common::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robostilt_common::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robostilt_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robostilt_common': ['/home/fernandomierhicks/robostilt/src/robostilt_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robostilt_common::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robostilt_common::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robostilt_common::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robostilt_common::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robostilt_common::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robostilt_common::RobotState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robostilt_common::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d7a63dca06bfd67e6e09bd329a9cf32";
  }

  static const char* value(const ::robostilt_common::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d7a63dca06bfd67ULL;
  static const uint64_t static_value2 = 0xe6e09bd329a9cf32ULL;
};

template<class ContainerAllocator>
struct DataType< ::robostilt_common::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robostilt_common/RobotState";
  }

  static const char* value(const ::robostilt_common::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robostilt_common::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 STATE_READY=0\n\
int32 STATE_FAULTED=1\n\
int32 STATE_BUSY_MOVING=2\n\
int32 STATE_BUSY_COMPUTING=3\n\
\n\
int32 FAULT_CLEAR=0\n\
int32 FAULT_ESTOP=1\n\
int32 FAULT_EFFORT=2\n\
int32 FAULT_TRAJECTORY=3\n\
\n\
\n\
Header header\n\
\n\
int32 state\n\
string state_string\n\
\n\
int32 fault\n\
string fault_string\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robostilt_common::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robostilt_common::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.state_string);
      stream.next(m.fault);
      stream.next(m.fault_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robostilt_common::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robostilt_common::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "state_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state_string);
    s << indent << "fault: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fault);
    s << indent << "fault_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fault_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_ROBOTSTATE_H
