// Generated by gencpp from file robostilt_common/SetPosition.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_SETPOSITION_H
#define ROBOSTILT_COMMON_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <robostilt_common/SetPositionRequest.h>
#include <robostilt_common/SetPositionResponse.h>


namespace robostilt_common
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace robostilt_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robostilt_common::SetPosition > {
  static const char* value()
  {
    return "7d0c2d81f2531fd032e1874cd31efec8";
  }

  static const char* value(const ::robostilt_common::SetPosition&) { return value(); }
};

template<>
struct DataType< ::robostilt_common::SetPosition > {
  static const char* value()
  {
    return "robostilt_common/SetPosition";
  }

  static const char* value(const ::robostilt_common::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::robostilt_common::SetPositionRequest> should match 
// service_traits::MD5Sum< ::robostilt_common::SetPosition > 
template<>
struct MD5Sum< ::robostilt_common::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::SetPosition >::value();
  }
  static const char* value(const ::robostilt_common::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::SetPositionRequest> should match 
// service_traits::DataType< ::robostilt_common::SetPosition > 
template<>
struct DataType< ::robostilt_common::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::SetPosition >::value();
  }
  static const char* value(const ::robostilt_common::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robostilt_common::SetPositionResponse> should match 
// service_traits::MD5Sum< ::robostilt_common::SetPosition > 
template<>
struct MD5Sum< ::robostilt_common::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::SetPosition >::value();
  }
  static const char* value(const ::robostilt_common::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::SetPositionResponse> should match 
// service_traits::DataType< ::robostilt_common::SetPosition > 
template<>
struct DataType< ::robostilt_common::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::SetPosition >::value();
  }
  static const char* value(const ::robostilt_common::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_SETPOSITION_H
