// Generated by gencpp from file robostilt_common/SetSupportingLegsRequest.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_SETSUPPORTINGLEGSREQUEST_H
#define ROBOSTILT_COMMON_MESSAGE_SETSUPPORTINGLEGSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robostilt_common
{
template <class ContainerAllocator>
struct SetSupportingLegsRequest_
{
  typedef SetSupportingLegsRequest_<ContainerAllocator> Type;

  SetSupportingLegsRequest_()
    : indexes()
    , is_supporting_weight()  {
    }
  SetSupportingLegsRequest_(const ContainerAllocator& _alloc)
    : indexes(_alloc)
    , is_supporting_weight(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _indexes_type;
  _indexes_type indexes;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _is_supporting_weight_type;
  _is_supporting_weight_type is_supporting_weight;





  typedef boost::shared_ptr< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSupportingLegsRequest_

typedef ::robostilt_common::SetSupportingLegsRequest_<std::allocator<void> > SetSupportingLegsRequest;

typedef boost::shared_ptr< ::robostilt_common::SetSupportingLegsRequest > SetSupportingLegsRequestPtr;
typedef boost::shared_ptr< ::robostilt_common::SetSupportingLegsRequest const> SetSupportingLegsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robostilt_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robostilt_common': ['/home/fernandomierhicks/robostilt/src/robostilt_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebc461152beaceb4199f054fe9699d75";
  }

  static const char* value(const ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebc461152beaceb4ULL;
  static const uint64_t static_value2 = 0x199f054fe9699d75ULL;
};

template<class ContainerAllocator>
struct DataType< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robostilt_common/SetSupportingLegsRequest";
  }

  static const char* value(const ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] indexes\n\
bool[] is_supporting_weight\n\
";
  }

  static const char* value(const ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.indexes);
      stream.next(m.is_supporting_weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSupportingLegsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robostilt_common::SetSupportingLegsRequest_<ContainerAllocator>& v)
  {
    s << indent << "indexes[]" << std::endl;
    for (size_t i = 0; i < v.indexes.size(); ++i)
    {
      s << indent << "  indexes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.indexes[i]);
    }
    s << indent << "is_supporting_weight[]" << std::endl;
    for (size_t i = 0; i < v.is_supporting_weight.size(); ++i)
    {
      s << indent << "  is_supporting_weight[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.is_supporting_weight[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_SETSUPPORTINGLEGSREQUEST_H
