// Generated by gencpp from file robostilt_common/StepForward.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_STEPFORWARD_H
#define ROBOSTILT_COMMON_MESSAGE_STEPFORWARD_H

#include <ros/service_traits.h>


#include <robostilt_common/StepForwardRequest.h>
#include <robostilt_common/StepForwardResponse.h>


namespace robostilt_common
{

struct StepForward
{

typedef StepForwardRequest Request;
typedef StepForwardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepForward
} // namespace robostilt_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robostilt_common::StepForward > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::robostilt_common::StepForward&) { return value(); }
};

template<>
struct DataType< ::robostilt_common::StepForward > {
  static const char* value()
  {
    return "robostilt_common/StepForward";
  }

  static const char* value(const ::robostilt_common::StepForward&) { return value(); }
};


// service_traits::MD5Sum< ::robostilt_common::StepForwardRequest> should match 
// service_traits::MD5Sum< ::robostilt_common::StepForward > 
template<>
struct MD5Sum< ::robostilt_common::StepForwardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::StepForward >::value();
  }
  static const char* value(const ::robostilt_common::StepForwardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::StepForwardRequest> should match 
// service_traits::DataType< ::robostilt_common::StepForward > 
template<>
struct DataType< ::robostilt_common::StepForwardRequest>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::StepForward >::value();
  }
  static const char* value(const ::robostilt_common::StepForwardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robostilt_common::StepForwardResponse> should match 
// service_traits::MD5Sum< ::robostilt_common::StepForward > 
template<>
struct MD5Sum< ::robostilt_common::StepForwardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::StepForward >::value();
  }
  static const char* value(const ::robostilt_common::StepForwardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::StepForwardResponse> should match 
// service_traits::DataType< ::robostilt_common::StepForward > 
template<>
struct DataType< ::robostilt_common::StepForwardResponse>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::StepForward >::value();
  }
  static const char* value(const ::robostilt_common::StepForwardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_STEPFORWARD_H
