// Generated by gencpp from file robostilt_common/StopAll.msg
// DO NOT EDIT!


#ifndef ROBOSTILT_COMMON_MESSAGE_STOPALL_H
#define ROBOSTILT_COMMON_MESSAGE_STOPALL_H

#include <ros/service_traits.h>


#include <robostilt_common/StopAllRequest.h>
#include <robostilt_common/StopAllResponse.h>


namespace robostilt_common
{

struct StopAll
{

typedef StopAllRequest Request;
typedef StopAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopAll
} // namespace robostilt_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robostilt_common::StopAll > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::robostilt_common::StopAll&) { return value(); }
};

template<>
struct DataType< ::robostilt_common::StopAll > {
  static const char* value()
  {
    return "robostilt_common/StopAll";
  }

  static const char* value(const ::robostilt_common::StopAll&) { return value(); }
};


// service_traits::MD5Sum< ::robostilt_common::StopAllRequest> should match 
// service_traits::MD5Sum< ::robostilt_common::StopAll > 
template<>
struct MD5Sum< ::robostilt_common::StopAllRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::StopAll >::value();
  }
  static const char* value(const ::robostilt_common::StopAllRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::StopAllRequest> should match 
// service_traits::DataType< ::robostilt_common::StopAll > 
template<>
struct DataType< ::robostilt_common::StopAllRequest>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::StopAll >::value();
  }
  static const char* value(const ::robostilt_common::StopAllRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robostilt_common::StopAllResponse> should match 
// service_traits::MD5Sum< ::robostilt_common::StopAll > 
template<>
struct MD5Sum< ::robostilt_common::StopAllResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robostilt_common::StopAll >::value();
  }
  static const char* value(const ::robostilt_common::StopAllResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robostilt_common::StopAllResponse> should match 
// service_traits::DataType< ::robostilt_common::StopAll > 
template<>
struct DataType< ::robostilt_common::StopAllResponse>
{
  static const char* value()
  {
    return DataType< ::robostilt_common::StopAll >::value();
  }
  static const char* value(const ::robostilt_common::StopAllResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSTILT_COMMON_MESSAGE_STOPALL_H
