#example
robostilt:
  dimensions:
    third_frame_prismatic_offset : 0.0
    leg_1_offset: -0.4
    leg_3_offset: -0.4
    leg_5_offset: -0.4
    leg_2_offset: -0.4
    leg_4_offset: -0.4
    leg_6_offset: -0.4
    third_frame_revolute_offset : 0.0
