#example
robostilt:
  dimensions:
    #Offsets ensure that commanding a zero position puts the joint in the expected position:
    #Foot at the same level as bottom frame
    #Prismatic  ??
    #Revolute straigth
    #***Offsets can be implemented by changing the pysical location of the origin of each link. Currenlty implemented
    #***Offsets can also be implemented on the motor control interface. Not as nice as doing it in the URDF
    ##NOT USED...
    third_frame_prismatic_offset : 0.0
    leg_1_offset: 0.0
    leg_3_offset:  0.0
    leg_5_offset:  0.0
    leg_2_offset:  0.0
    leg_4_offset:  0.00
    leg_6_offset:  0.0
    third_frame_revolute_offset : 0.0

    nominal_walking_height: -1.8  #How much to extend legs from zero position when walking normally.

    obstacle_area_length_x: 0.5 
    obstacle_area_width_y: 1.5

  raising_frame:
    velocity: 0.2
    efforts:
      upper: 10
      lower: -35
  
  lowering_legs:
    velocity: 0.1
    efforts:
      upper: 30
      lower: 0

  raising_legs:
    velocity: 0.5
    efforts:
      upper: 75
      lower: -75

  moving_prismatic:
    velocity: 0.1
    efforts:
      upper: 50
      lower: -50


  
  efforts:
    boost_level: # at beginning of motion effort limit is increased to this for boost_duration, then it falls to a predetermined level
      upper: 100
      lower: -100

  durations:
    boost_duration: 1.0
  
  angles:
    leveling_max_error: 0.0872665  #triggers alarm if level is ever off by this much.


  


    
    


