(cl:in-package robostilt_common-msg)
(cl:export '(HEADER-VAL
          HEADER
          NAME-VAL
          NAME
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          EFFORT-VAL
          EFFORT
          EFFORT_LIMIT-VAL
          EFFORT_LIMIT
          POSITION_SETPOINT-VAL
          POSITION_SETPOINT
          MANIPULATION-VAL
          MANIPULATION
          PROGRESS-VAL
          PROGRESS
          IS_MOVING-VAL
          IS_MOVING
          IS_READY-VAL
          IS_READY
          HAS_BEEN_HOMED-VAL
          HAS_BEEN_HOMED
          IS_SUPPORTING_WEIGHT-VAL
          IS_SUPPORTING_WEIGHT
          HAVE_ALL_BEEN_HOMED-VAL
          HAVE_ALL_BEEN_HOMED
          ALL_ARE_READY-VAL
          ALL_ARE_READY
))