(cl:in-package robostilt_common-msg)
(cl:export '(NAME-VAL
          NAME
          INDEX-VAL
          INDEX
          POSITION-VAL
          POSITION
          POSITION_SETPOINT-VAL
          POSITION_SETPOINT
          POSITION_GOAL-VAL
          POSITION_GOAL
          VELOCITY-VAL
          VELOCITY
          VELOCITY_SETPOINT-VAL
          VELOCITY_SETPOINT
          EFFORT-VAL
          EFFORT
          EFFORT_LIMIT_UPPER-VAL
          EFFORT_LIMIT_UPPER
          EFFORT_LIMIT_LOWER-VAL
          EFFORT_LIMIT_LOWER
          EFFORT_FAULT_EXPECTED-VAL
          EFFORT_FAULT_EXPECTED
          MANIPULATION-VAL
          MANIPULATION
          PROGRESS-VAL
          PROGRESS
          IS_MOVING-VAL
          IS_MOVING
          IS_READY-VAL
          IS_READY
          HAS_BEEN_HOMED-VAL
          HAS_BEEN_HOMED
          IS_SUPPORTING_WEIGHT-VAL
          IS_SUPPORTING_WEIGHT
))