# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robostilt_common/ActuatorsState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robostilt_common.msg
import std_msgs.msg

class ActuatorsState(genpy.Message):
  _md5sum = "49208e592a412e2ba9a50e6f208bf8a1"
  _type = "robostilt_common/ActuatorsState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# This is a message that holds the state of all actuators as an array.

uint8 COUNT=8
uint8 THIRD_FRAME_PRISMATIC = 0
uint8 LEG_1 = 1
uint8 LEG_2 = 2
uint8 LEG_3 = 3
uint8 LEG_4 = 4
uint8 LEG_5 = 5
uint8 LEG_6 = 6
uint8 THIRD_FRAME_REVOLUTE = 7


Header header

SingleActuator[] actuators
bool have_all_been_homed
bool all_are_ready
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: robostilt_common/SingleActuator
# This is a message that holds extended data for a single actuator

string  name
int32   index

float64 position
float64 position_setpoint   #trajectorized setpoint TODO
float64 position_goal       #long term goal

float64 velocity
float64 velocity_setpoint   #trajectorized velocity TODO

float64 effort
float64 effort_limit


float32 manipulation
float32 progress

bool is_moving
bool is_ready
bool has_been_homed
bool is_supporting_weight




"""
  # Pseudo-constants
  COUNT = 8
  THIRD_FRAME_PRISMATIC = 0
  LEG_1 = 1
  LEG_2 = 2
  LEG_3 = 3
  LEG_4 = 4
  LEG_5 = 5
  LEG_6 = 6
  THIRD_FRAME_REVOLUTE = 7

  __slots__ = ['header','actuators','have_all_been_homed','all_are_ready']
  _slot_types = ['std_msgs/Header','robostilt_common/SingleActuator[]','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,actuators,have_all_been_homed,all_are_ready

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActuatorsState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.actuators is None:
        self.actuators = []
      if self.have_all_been_homed is None:
        self.have_all_been_homed = False
      if self.all_are_ready is None:
        self.all_are_ready = False
    else:
      self.header = std_msgs.msg.Header()
      self.actuators = []
      self.have_all_been_homed = False
      self.all_are_ready = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.actuators)
      buff.write(_struct_I.pack(length))
      for val1 in self.actuators:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_i7d2f4B().pack(_x.index, _x.position, _x.position_setpoint, _x.position_goal, _x.velocity, _x.velocity_setpoint, _x.effort, _x.effort_limit, _x.manipulation, _x.progress, _x.is_moving, _x.is_ready, _x.has_been_homed, _x.is_supporting_weight))
      _x = self
      buff.write(_get_struct_2B().pack(_x.have_all_been_homed, _x.all_are_ready))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.actuators is None:
        self.actuators = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actuators = []
      for i in range(0, length):
        val1 = robostilt_common.msg.SingleActuator()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 72
        (_x.index, _x.position, _x.position_setpoint, _x.position_goal, _x.velocity, _x.velocity_setpoint, _x.effort, _x.effort_limit, _x.manipulation, _x.progress, _x.is_moving, _x.is_ready, _x.has_been_homed, _x.is_supporting_weight,) = _get_struct_i7d2f4B().unpack(str[start:end])
        val1.is_moving = bool(val1.is_moving)
        val1.is_ready = bool(val1.is_ready)
        val1.has_been_homed = bool(val1.has_been_homed)
        val1.is_supporting_weight = bool(val1.is_supporting_weight)
        self.actuators.append(val1)
      _x = self
      start = end
      end += 2
      (_x.have_all_been_homed, _x.all_are_ready,) = _get_struct_2B().unpack(str[start:end])
      self.have_all_been_homed = bool(self.have_all_been_homed)
      self.all_are_ready = bool(self.all_are_ready)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.actuators)
      buff.write(_struct_I.pack(length))
      for val1 in self.actuators:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_i7d2f4B().pack(_x.index, _x.position, _x.position_setpoint, _x.position_goal, _x.velocity, _x.velocity_setpoint, _x.effort, _x.effort_limit, _x.manipulation, _x.progress, _x.is_moving, _x.is_ready, _x.has_been_homed, _x.is_supporting_weight))
      _x = self
      buff.write(_get_struct_2B().pack(_x.have_all_been_homed, _x.all_are_ready))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.actuators is None:
        self.actuators = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.actuators = []
      for i in range(0, length):
        val1 = robostilt_common.msg.SingleActuator()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 72
        (_x.index, _x.position, _x.position_setpoint, _x.position_goal, _x.velocity, _x.velocity_setpoint, _x.effort, _x.effort_limit, _x.manipulation, _x.progress, _x.is_moving, _x.is_ready, _x.has_been_homed, _x.is_supporting_weight,) = _get_struct_i7d2f4B().unpack(str[start:end])
        val1.is_moving = bool(val1.is_moving)
        val1.is_ready = bool(val1.is_ready)
        val1.has_been_homed = bool(val1.has_been_homed)
        val1.is_supporting_weight = bool(val1.is_supporting_weight)
        self.actuators.append(val1)
      _x = self
      start = end
      end += 2
      (_x.have_all_been_homed, _x.all_are_ready,) = _get_struct_2B().unpack(str[start:end])
      self.have_all_been_homed = bool(self.have_all_been_homed)
      self.all_are_ready = bool(self.all_are_ready)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i7d2f4B = None
def _get_struct_i7d2f4B():
    global _struct_i7d2f4B
    if _struct_i7d2f4B is None:
        _struct_i7d2f4B = struct.Struct("<i7d2f4B")
    return _struct_i7d2f4B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
