(cl:defpackage robostilt_common-srv
  (:use )
  (:export
   "LOWERLEGSONFRAME"
   "<LOWERLEGSONFRAME-REQUEST>"
   "LOWERLEGSONFRAME-REQUEST"
   "<LOWERLEGSONFRAME-RESPONSE>"
   "LOWERLEGSONFRAME-RESPONSE"
   "SETPOSITION"
   "<SETPOSITION-REQUEST>"
   "SETPOSITION-REQUEST"
   "<SETPOSITION-RESPONSE>"
   "SETPOSITION-RESPONSE"
  ))

