<?xml version="1.0"?>
<robot name="robostilt" xmlns:xacro="http://www.ros.org/wiki/xacro" >  <!-- ROBOT NAME -->
<!-- PROPERTIES -->
  <xacro:property name="leg_length" value="1.0" />
  <xacro:property name="frame_length_x" value="1.5" />
  <xacro:property name="frame_length_y" value="1.0" />
  <xacro:property name="frame_thickness" value="0.09" />


  <xacro:property name="limit_leg_lower" value="-0.9" />
  <xacro:property name="limit_leg_upper" value="-0.1" />
  <xacro:property name="limit_leg_velocity" value="0.5" />
  <xacro:property name="limit_leg_effort" value="1000.0" />

  <xacro:property name="limit_third_frame_prismatic_lower" value="${-1*frame_thickness}" />
  <xacro:property name="limit_third_frame_prismatic_upper" value="${-1*frame_length_x/3.0}" />
  <xacro:property name="limit_third_frame_prismatic_velocity" value="0.5" />
  <xacro:property name="limit_third_frame_prismatic_effort" value="1000.0" />

  <xacro:property name="limit_third_frame_revolute_lower" value="-0.5" />
  <xacro:property name="limit_third_frame_revolute_upper" value="0.5" />
  <xacro:property name="limit_third_frame_revolute_velocity" value="0.5" />
  <xacro:property name="limit_third_frame_revolute_effort" value="1000.0" />


<!-- Friction and dynamics -->
<xacro:macro name="friction" >
      <mu1>0.6</mu1>
      <mu2>0.6</mu2>
</xacro:macro>
  <xacro:property name="damping" value="1.5" />
  <xacro:property name="damping_friction" value="1.0" />


<!-- MACROS -->
  <!-- Frames -->
   <xacro:macro name="frame_link" params="link_name material reflect" >
      <link name="${link_name}">      
        <visual> <!-- X beam -->
          <geometry>
            <box size="${frame_length_x-frame_thickness*1.1} ${frame_thickness} ${frame_thickness}"/>
          </geometry>        
          <material name="${material}"/>
        </visual>
        <visual>   <!-- Y beam -->
          <geometry>
            <box size="${frame_thickness} ${frame_length_y-frame_thickness*1.1} ${frame_thickness}"/>
          </geometry>
          <origin rpy="0 0 0" xyz="${-1*reflect*frame_length_x/2.0} 0 0"/>        
          <material name="${material}"/>
        </visual>

        <collision>
        <geometry>
            <box size="${frame_length_x-frame_thickness*1.1} ${frame_thickness} ${frame_thickness}"/>
          </geometry>       
        </collision>
        <collision><!-- Y beam -->
        <geometry>
            <box size="${frame_thickness} ${frame_length_y-frame_thickness*1.1} ${frame_thickness}"/>
          </geometry>
          <origin rpy="0 0 0" xyz="${frame_length_x/2.0} 0 0"/>        
        </collision>

        <inertial>
          <mass value="1.0" />
          <inertia ixx="0.008" ixy="0.0" ixz="0.0" iyy="0.08" iyz="0.0" izz="0.08" />
        </inertial>
      </link>

      <gazebo reference="${link_name}">
          <xacro:friction/>
          <xacro:gazebo_color material="${material}"/>
      </gazebo> 
    </xacro:macro>

  <!-- Legs -->
    <xacro:macro name="leg" params="suffix material parent x y">

      <link name="leg_${suffix}">

        <visual>
          <geometry>
            <cylinder length="${leg_length}" radius="${frame_thickness/2.0}"/>
          </geometry>
          <origin rpy="0 0 0" xyz="0.0 0.0 ${leg_length/2.0}"/>
          <material name="${material}"/>
        </visual>

        <collision>
          <geometry>
            <cylinder length="${leg_length}" radius="${frame_thickness/2.0}"/>
          </geometry>
        </collision>

        <inertial>
          <mass value="1.0" />
          <inertia ixx="0.08" ixy="0.0" ixz="0.0" iyy="0.08" iyz="0.0" izz="0.001" />
        </inertial>
      </link>

      <joint name="${parent}_to_leg_${suffix}" type="prismatic">
        <parent link="${parent}"/>
        <child link="leg_${suffix}"/>
        <limit effort="${limit_leg_effort}" lower="${limit_leg_lower}" upper="${limit_leg_upper}" velocity="${limit_leg_velocity}"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 0 0" xyz="${x} ${y} 0.0"/>
        <dynamics damping="${damping}" friction="${damping_friction}" />
      </joint>

      
      <gazebo reference="leg_${suffix}">
        <xacro:friction/>
        <xacro:gazebo_color material="${material}"/>
      </gazebo>     

      <transmission name="leg_${suffix}_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${parent}_to_leg_${suffix}">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="leg_${suffix}_motor">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>


    </xacro:macro>

<!-- COLORS -->
<xacro:include filename="$(find robostilt_description)/urdf/materials.xacro"/>

<xacro:macro name="gazebo_color" params="material" >
  <xacro:if value="${material=='Orange'}">
    <material>Gazebo/Orange</material>
  </xacro:if>
  <xacro:if value="${material=='Yellow'}">
    <material>Gazebo/Yellow</material>
  </xacro:if>
</xacro:macro>




<!-- FRAMES -->

     <!-- Even frame --> 
  <xacro:frame_link link_name="base_link" material="Orange" reflect="1"/>
  


  <link name="third_frame"> <!-- Revolute joint --> 
      <visual>
        <geometry>
          <cylinder length="${frame_thickness}" radius="${frame_thickness/2.0}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <material name="Yellow"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${frame_thickness}" radius="${frame_thickness/2.0}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
      </inertial>
  </link>
  <gazebo reference="third_frame">
         <xacro:friction/>
        <xacro:gazebo_color material="Yellow"/>
  </gazebo> 



  <joint name="base_link_to_third_frame" type="prismatic">
      <parent link="base_link"/>
      <child link="third_frame"/>
      <origin xyz="0.0 0.0 ${frame_thickness}"/>
      <axis xyz="1 0 0"/>
      <limit effort="${limit_third_frame_prismatic_effort}" lower="${limit_third_frame_prismatic_lower}" upper="${limit_third_frame_prismatic_upper}" velocity="${limit_third_frame_prismatic_velocity}"/>
       <dynamics damping="${damping}" friction="${damping_friction}" />
  </joint>

  <transmission name="base_link_to_third_frame_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_link_to_third_frame">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="third_frame_prismatic_motor">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
 
   <!-- Odd frame --> 
   <xacro:frame_link link_name="odd_frame" material="Yellow" reflect="-1"/>


  <joint name="third_frame_to_odd_frame" type="revolute">
        <parent link="third_frame"/>
        <child link="odd_frame"/>
        <origin xyz="0.0 0.0 ${frame_thickness}"/>
        <axis xyz="0 0 1"/>
        <limit effort="${limit_third_frame_revolute_effort}" lower="${limit_third_frame_revolute_lower}" upper="${limit_third_frame_revolute_upper}" velocity="${limit_third_frame_revolute_velocity}"/>
         <dynamics damping="${damping}" friction="${damping_friction}" />
  </joint>
   <transmission name="third_frame_to_odd_frame_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="third_frame_to_odd_frame">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="third_frame_revolute_motor">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>






<!-- LEGS -->

 <xacro:leg suffix="1" material="Yellow" parent="odd_frame" x="${frame_length_x/2.0}" y="${frame_length_y/2.0}"/>

  <xacro:leg suffix="3" material="Yellow" parent="odd_frame" x="${frame_length_x/2.0}" y="${-1*frame_length_y/2.0}"/>

  <xacro:leg suffix="5" material="Yellow" parent="odd_frame" x="${-1*frame_length_x/2.0}" y="0"/>



  <xacro:leg suffix="2" material="Orange" parent="base_link" x="${frame_length_x/2.0}" y="0"/>


  <xacro:leg suffix="4" material="Orange" parent="base_link" x="${-1*frame_length_x/2.0}" y="${frame_length_y/2.0}"/>

  <xacro:leg suffix="6" material="Orange" parent="base_link" x="${-1*frame_length_x/2.0} " y="${-1*frame_length_y/2.0}"/>
   

<!-- GAZEBO -->


<xacro:include filename="$(find robostilt_description)/urdf/robostilt.gazebo"/>





</robot>