robostilt:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  
  # Position Controllers ---------------------------------------
# Loads zero PID constants for safety. PID gets updated on separate call. 

  leg_pid_gains: {p: 10.0, i: 0.01, d: 0.0}
  third_frame_revolute_pid_gains: {p: 100.0, i: 0.01, d: 0.0}
  third_frame_prismatic_pid_gains: {p: 100.0, i: 0.01, d: 0.0}

  leg_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_leg_2
    pid: {p: 0.0, i: 0.0, d: 0.0}

  leg_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_leg_4
    pid: {p: 0.0, i: 0.0, d: 0.0}

  leg_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_leg_6
    pid: {p: 0.0, i: 0.0, d: 0.0}

  leg_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: odd_frame_to_leg_1
    pid: {p: 0.0, i: 0.0, d: 0.0}

  leg_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: odd_frame_to_leg_3
    pid: {p: 0.0, i: 0.0, d: 0.0}

  leg_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: odd_frame_to_leg_5
    pid: {p: 0.0, i: 0.0, d: 0.0}

  third_frame_revolute_position_controller:
    type: effort_controllers/JointPositionController
    joint: third_frame_to_odd_frame
    pid: {p: 0.0, i: 0.0, d: 0.0}

  third_frame_prismatic_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_third_frame
    pid: {p: 0.0, i: 0.0, d: 0.0}



